spring:
  jpa:
    show-sql: false
    properties:
      hibernate.format_sql: false
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  application:
    name: Yard_Sale_Messaging
  h2:
    console:
      path: /h2
      enabled: true
  profiles:
    active: dev
server:
  port: 8083
logging:
  level:
    org.springframework.security: debug